1_week 2_task
Ypostolov/SelfEducation pull request #8
Opened 2019-07-16 13:00 UTC by Ypostolov

Please check

2019-07-17 08:00 UTC, LuxoftAKutsan requested changes

2019-07-17 08:00 UTC, LuxoftAKutsan commented on week_1/task_2/Task_2.cpp
> +      else if(string_2 < string_1 && string_2 < string_3){
@Ypostolov  fix style

2019-07-18 15:41 UTC, Ypostolov commented on week_1/task_2/Task_2.cpp
> +      else if(string_2 < string_1 && string_2 < string_3){
Fixed in d54001a52ee817a685e4e77011d7f0cd8e922e53.
Please check.

2019-07-20 17:22 UTC, alexkutsan approved these changes

2019-07-20 17:22 UTC, merged